---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Heading 1
- type: document
  path: about/index.md
  label: About
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
- type: document
  path: test
  label: Test
upload_dir: ''
public_path: https://res.cloudinary.com/{{ CLOUD_NAME }}/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
